run:
  skip-dirs:
    components

linters:
  enable-all: true
  disable:
    - cyclop
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exhaustivestruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofumpt
    - golint
    - gomnd
    - gosec
    - gosimple
    - ifshort
    - interfacer
    - ireturn
    - lll
    - maligned
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - nlreturn
    - paralleltest
    - scopelint
    - staticcheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
